# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 29 Oct 2019 09:27:07 +0000
*               @ALL          0
*               @user         8
