<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: sakhnik
 * Date: Sat, 09 Nov 2019 07:37:26 +0000
 */

$conf['title'] = 'English';
$conf['lang'] = 'uk';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
$conf['tpl']['bootstrap3']['useAlternativeToolbarIcons'] = 0;

// end auto-generated content
